name: C++ CI action demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
     - uses: actions/checkout@v2
     - name: cmake
     - run: |
        mkdir build
        cd build
        cmake ..
