name: C++ CI action demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v2
    - name: cmake
    run: mkdir build && cd build && cmake ..
    - name: make
    run: cd build && make
    - name: Run googletest
    run: cd build && ./test_FriendlyCode
